version: "3"

services:
  ########################################
  # PostgreSQL
  ########################################
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-reader}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    volumes:
      - db-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"

  #######################################
  # Imaginary: Image proxy
  #######################################
  imaginary:
    image: h2non/imaginary:latest
    command: -enable-url-source -http-cache-ttl 172800
    environment:
      - MALLOC_ARENA_MAX=2
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    restart: always
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  ########################################
  # API
  ########################################
  api:
    build: .
    image: "ncarlier/readflow:latest"
    restart: always
    depends_on:
      - db
    networks:
      - web
      - internal
    environment:
      - APP_DB=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB:-reader}?sslmode=disable
      - APP_BROKER=${EVENT_BROKER}
      - APP_SENTRY_DSN=${SENTRY_DSN}
      - APP_LISTEN_METRICS=:9090
      - APP_IMAGE_PROXY=http://imaginary:9000
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:api.${FQDN}"
      - "traefik.docker.network=${GW_NETWORK_NAME}"

#  ########################################
#  # Webapp
#  ########################################
#  app:
#    build: ./ui/
#    image: "ncarlier/readflow-app:latest"
#    restart: always
#    networks:
#      - web
#      - internal
#    labels:
#      - "traefik.port=80"
#      - "traefik.frontend.rule=Host:${FQDN}"
#      - "traefik.docker.network=${GW_NETWORK_NAME}"

networks:
  web:
    external:
      name: "${GW_NETWORK_NAME}"
  internal:
    external: false

volumes:
  db-data:
