[build]
  command = "npm run build"
  publish = "landing/out"

[[plugins]]
  package = "@netlify/plugin-nextjs@3.2.2"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
